spring.application.name=Spring1

#單庫:brad
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/brad?userSSL=false&serverTimezone=Asia/Taipei&charcaterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root